services:
  consul:
    image: hashicorp/consul:1.19
    container_name: local-consul
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - local-postgres-data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: local-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  local-postgres-data:
