
# ===== SERVER =====
server.port=8081
# B\u1eadt t\u00ednh n\u0103ng hi\u1ec3n th\u1ecb tin nh\u1eafn l\u1ed7i chi ti\u1ebft ra ngo\u00e0i API
server.error.include-message=always


# ===== DATABASE =====
spring.datasource.url=jdbc:postgresql://localhost:5432/monolithic_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
hocviec.jwt.signer-key=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789

spring.cloud.compatibility-verifier.enabled=false
spring.cloud.consul.enabled=false
spring.cloud.discovery.enabled=false

#==== Consul =====
# spring.application.name=book-service
# spring.cloud.consul.host=localhost
# spring.cloud.consul.port=8500
# spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}

# Ép service sử dụng IP thực tế khi đăng ký lên Consul
# spring.cloud.consul.discovery.prefer-ip-address=true
# Tự động hủy đăng ký service trên Consul nếu nó không còn hoạt động (Unhealthy) sau 10 giây
# spring.cloud.consul.discovery.health-check-critical-timeout=10s

# management.endpoints.web.exposure.include=health